global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'shoppa_server'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']