version: "3.9"

services:
  backend:
    container_name: shoppa_backend
    build: ./backend
    ports:
      - 8000:8000
    # restart: 'on-failure'
    environment:
      - PORT=8000
      - DB_URI = mongodb+srv://shoppateam:shoppapassword@shoppa.2xhzdqb.mongodb.net/shoppa
      - JWT_SECRET = admin
      - JWT_EXPIRE = 1d
      - STRIPE_API_KEY = pk_test_51M52wBSDeV9d1NY7b6jh5mryxSCHtvKOrrdcaY1oHc3PkjRoVIS8wtiAPsrZmp23giuyIzJnG92c1u2nWzh5XaEb00gRj6JEl6
      - STRIPE_SECRET_KEY = sk_test_51M52wBSDeV9d1NY7ElwhBQuMmhCg11uI2eWliOeZywaDHUAxFyg89thNbeJktPWmxDFBG6GsgN2Pvv0aDSHbfCWq002KNWxQMe
      - CLOUDINARY_API_KEY = 157382137221323
      - CLOUDINARY_API_SECRET = sQMbpEBmnCD68Gty0ZVbEwXnSGg
      - CLOUDINARY_NAME = dlqmybsfl
    volumes:
      - ./backend:/usr/src/app
      # - ../shoppa-logs:/usr/src/app/logs
      # - ./shoppa-logs:/usr/src/app/logs

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor_container
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./backend/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./backend/grafana/provisioning:/etc/grafana/provisioning
      - ./backend/grafana/data:/var/lib/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - 4000:3000

  frontend:
    container_name: shoppa_frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
