{
 "title": "Shoppa",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"shoppa_frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_user_seconds_total{name=\"shoppa_backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"shoppa_frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"shoppa_backend\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}